In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Tensors

In [2]:
x = torch.ones(3,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.4394, 0.1882],
        [0.6143, 0.7864]])


In [3]:
x = torch.empty(3,2)
print(x)

tensor([[1.0877e-34, 0.0000e+00],
        [3.5032e-44, 0.0000e+00],
        [       nan, 1.0000e+00]])


In [4]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
torch.linspace(0,2,steps=10)

tensor([0.0000, 0.2222, 0.4444, 0.6667, 0.8889, 1.1111, 1.3333, 1.5556, 1.7778,
        2.0000])

In [6]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

# Slicing and Reshaping Tensors

In [7]:
x = torch.tensor([[1,2],[3,4]])
print(x[:1])
print(x[:,1])
print(x[:,:1])

tensor([[1, 2]])
tensor([2, 4])
tensor([[1],
        [3]])


In [8]:
x[0,0].item()

1

In [9]:
x = torch.rand(5,2)
print(x)
print(x.reshape(2,5))

tensor([[0.3851, 0.0133],
        [0.6994, 0.9162],
        [0.6999, 0.3274],
        [0.4727, 0.4367],
        [0.9625, 0.7117]])
tensor([[0.3851, 0.0133, 0.6994, 0.9162, 0.6999],
        [0.3274, 0.4727, 0.4367, 0.9625, 0.7117]])


In [10]:
print(x)

tensor([[0.3851, 0.0133],
        [0.6994, 0.9162],
        [0.6999, 0.3274],
        [0.4727, 0.4367],
        [0.9625, 0.7117]])


In [11]:
print(x.reshape(10,-1))

tensor([[0.3851],
        [0.0133],
        [0.6994],
        [0.9162],
        [0.6999],
        [0.3274],
        [0.4727],
        [0.4367],
        [0.9625],
        [0.7117]])


# Operations on Tensors

In [12]:
x = torch.ones(2,4)
y = torch.ones(2,4)

In [13]:
z = x + y
print(z)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [14]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])


# Numpy vs Pytorch

In [16]:
x = torch.ones(3,2)

In [17]:
x_np = x.numpy()
print(type(x),type(x_np))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [18]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[ 0.69735955 -0.94837106  0.44088682 -0.70254021  0.82737394]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 0.6974, -0.9484,  0.4409, -0.7025,  0.8274], dtype=torch.float64)


In [19]:
np.add(a,1,out = a)
print(a)
print(a_pt)

[1.69735955 0.05162894 1.44088682 0.29745979 1.82737394]
tensor([1.6974, 0.0516, 1.4409, 0.2975, 1.8274], dtype=torch.float64)


In [20]:
%%time
for i in range(100):
    a = np.random.randn(1000,1000)
    b = np.random.randn(1000,1000)
    c = a + b

CPU times: user 8.73 s, sys: 47.5 ms, total: 8.78 s
Wall time: 9.79 s


In [21]:
%%time
for i in range(100):
    a = torch.randn([1000,1000])
    b = torch.randn([1000,1000]) 
    c = a + b

CPU times: user 1.29 s, sys: 10.5 ms, total: 1.3 s
Wall time: 1.3 s


In [22]:
%%time
for i in range(100):
    a = np.random.randn(100,100)
    b = np.random.randn(100,100)
    c = np.matmul(a,b)

CPU times: user 136 ms, sys: 107 ms, total: 242 ms
Wall time: 142 ms


In [23]:
%%time
for i in range(100):
    a = torch.randn([100,100])
    b = torch.randn([100,100]) 
    c = torch.matmul(a,b)

CPU times: user 30.4 ms, sys: 39.3 ms, total: 69.7 ms
Wall time: 47.9 ms


# Support of GPU (cuda)

In [24]:
print(torch.cuda.device_count())

1


In [26]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [27]:
cuda0 = torch.device('cuda:0')

In [28]:
a = torch.ones(3,2,device = cuda0)
b = torch.ones(3,2,device = cuda0)
c = a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [29]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [34]:
%%time
for i in range(10):
    a_np = np.random.rand(10000,10000)
    b_np = np.random.rand(10000,10000)
    np.add(b_np,a_np)

CPU times: user 17.3 s, sys: 314 ms, total: 17.6 s
Wall time: 17.8 s


In [35]:
%%time
for i in range(10):
    a_cpu = torch.randn([10000,10000])
    b_cpu = torch.randn([10000,10000])
    b_cpu.add_(a_cpu)

CPU times: user 13.6 s, sys: 218 ms, total: 13.8 s
Wall time: 13.9 s


In [37]:
%%time
for i in range(10):
    a_gpu = torch.randn([10000,10000], device = cuda0)
    b_gpu = torch.randn([10000,10000], device = cuda0)
    b_gpu.add_(a_gpu)

CPU times: user 1.72 ms, sys: 1.99 ms, total: 3.71 ms
Wall time: 2.89 ms




# Auto Differentiation

In [27]:
x = torch.ones([3,2], requires_grad = True)

In [28]:
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [29]:
y = x + 5

In [30]:
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [32]:
s = torch.sum(y)
print(s)

tensor(36., grad_fn=<SumBackward0>)


In [34]:
s.backward()

In [35]:
x.grad

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [8]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [9]:
t.backward()

In [10]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [20]:
x = torch.randn([20,1], requires_grad = True)
y = 3*x - 2

In [21]:
w = torch.tensor([1.],requires_grad = True)
b = torch.tensor([1.],requires_grad = True)

In [22]:
y_hat = w*x + b
loss = torch.sum((y_hat - y)**2)

In [23]:
loss

tensor(139.7273, grad_fn=<SumBackward0>)

In [24]:
loss.backward()

In [25]:
print(w.grad,b.grad)

tensor([-20.0233]) tensor([79.8027])


In [36]:
lr = 0.01

w = torch.tensor([1.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)

print(w.item(),b.item())

1.0 1.0


In [37]:
for i in range(10):

    x = torch.randn([20,1])
    y = 3*x -2

    y_hat = w*x + b
    loss = torch.sum((y_hat - y)**2)

    loss.backward()

    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

        w.grad.zero_()
        b.grad.zero_()
        
    print(w.item(), b.item())

1.8647135496139526 -0.31136012077331543
2.753509759902954 -1.1427112817764282
2.745932102203369 -1.4576307535171509
2.935887098312378 -1.7048060894012451
2.9676265716552734 -1.8238633871078491
2.9915201663970947 -1.896945834159851
2.9863030910491943 -1.9375718832015991
2.999332904815674 -1.963805079460144
2.991593360900879 -1.9781330823898315
2.9935362339019775 -1.98696768283844
